### ISSUE TITLE
Allow uploading the same endpoint to different catalogs

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#148]
To test: Go to the admin, upload an endpoint list to a catalog and then upload it to another catalog.

**Comment by panchicore** [comment]
The new upload of endpoints wont create its Services, because a Service with that URL was previously created.

**Comment by panchicore** [comment]
two options to proceed:

1. add to Service M2M relationships to Catalogs, that requires a lot of changes on website and api.
2. change the validation by adding new Service in db for each Catalog, this is recommended since would be easier to integrate on the website and api endpoint, the downside is that would result on duplicated data where is only diffd for its catalog, but flexible to modify single Services per catalog if needed.

Is there anything more that I would be considering here?

**Comment by ingenieroariel** [comment]
Having for example worldmap on any catalog would be counter productive with
the repetition.

On use case to consider is Service 1 Layer 1 on Catalog 1 and Service 1
Layer 2 on Catalog 2. While having Service 1 Layer 1,2 in Catalog 3.

From the two options you described, which one would allow this case better?

**Comment by panchicore** [comment]
sounds like if Endpoint, Service and Layer would need a M2M rel to Catalogs. But not sure.

If user uploads an EnpointList in one catalog, will scrap the Endpoints and attach Services and Layers to new/existing lists of catalogs without the necesity to harvest again the webservice. does it make sense?

example:

EndpointList A is added to C1, it contains S1 and L1.
EndpointList B is added to C2, it contains S2 and L2.
Endpoint X (shareable) is added to C1 and C2, it will add its S3 and L3 to all S's and L's what contains C1 and C2.

Then 2 Catalogs will result and:
S1 will have L1, L3.
S2 will have L2, L3.
X will have L3.

I am not sure. Please provide example if that is not correct.

**Comment by ingenieroariel** [comment]
Right - avoiding double harvesting is a goal.

For now, let's table the discussion about double harvesting and get a simple solution:
```Endpoints, Services and Layers on different catalogs are treated as different objects (instead of  unique key in url, let's do unique key in url + catalog id)```
```

**Comment by panchicore** [comment]
https://d1zjcuqflbd5k.cloudfront.net/files/acc_393543/1h6er?response-content-disposition=inline;%20filename=Screen%20Capture%20on%202016-08-12%20at%2021-32-38.gif&Expires=1471055877&Signature=M5pKinmxmXerPRJCnVAUrNEwW3RLzdsj~bfoudVrwNntgE5L1aeqc07g9Fx795WqJ3HZLeRzlgyuhwKTvItIwGMHLUZfasqPDV1Ri8BAFRl-eMoEOFEaRrYBcBZdnUUfzcEwyMO60BpmEV-pwqB3nGQJzLEyFm7Or9~c6tmYNQo_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA

**Comment by panchicore** [comment]
![Image of gif](http://d.pr/i/1h6er+)
