### ISSUE TITLE
Organize per catalog urls

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#149]
`/registry/<catalog_name>/api` -> API filtered on that catalog.
`/registry/<catalog_name>/csw` -> CSW endpoint filtered by that catalog.
`/registry/<catalog_name>/` -> Show registry index (Services list) for just that catalog.
`/registry/<catalog_name>/layers/map` -> Mapproxy endpoint for that layer
`/registry/` -> Show list of catalogs.

**Comment by panchicore** [comment]
sent PR https://github.com/cga-harvard/HHypermap/pull/150
