### ISSUE TITLE
update codebase to use proper logging

### ISSUE THREAD

**Issue by tomkralidis** [cga-harvard/HHypermap#177]
In each of our Python files, implement proper logging (in lieu of `print` statements` via the following:

```python
LOGGER = logging.getLogger(__name__)
...
LOGGER.info('test')
LOGGER.warning('careful')
```

**Comment by ingenieroariel** [comment]
I pushed a commit that fixes this in latest registry.

**Comment by ingenieroariel** [comment]
https://github.com/cga-harvard/HHypermap/commit/3ac723dcc57c1a17e46b1ad6a30789370af7f258
