### ISSUE TITLE
Verify the bounding boxes for ArcGIS services

### ISSUE THREAD

**Issue by JorgeMartinezG** [cga-harvard/HHypermap#196]
the Rio Olympic ones are not showing data and could be to the wrong BBOX being saved (or in the wrong spatial reference system). Include tests for transforming bounding boxes from other systems.

**url**: http://ngamaps.geointapps.org/arcgis/rest/services/RIO/Rio_Foundation_Transportation/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by ingenieroariel** [comment]
They were not showing up due to a problem in MapLoom. It's fixed.
