### ISSUE TITLE
Create option for very lightweight monitoring

### ISSUE THREAD

**Issue by blewis** [cga-harvard/HHypermap#235]
Currently monitoring takes about 90% of those needed for full reharvesting which doesn't make sense.  We need a lightweight quick way to know whether, most likely, everything is ok.  This will be a simple service request which should reduce this to 1% which means it could be done daily, with actual reharvesting being monthly perhaps.  This should result in more accurate uptime statistics using fewer resources, putting less load on remote servers, and provide better options for search results ranking.

**Comment by capooti** [comment]
This is in place now using the REGISTRY_SKIP_LAYERS_CHECK setting.
