### ISSUE TITLE
pycsw endpoint must be public

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#244]
Currently, pycsw endpoint (for example http://hh.worldmap.harvard.edu/registry/hypermap/csw?service=CSW&version=2.0.2&request=GetCapabilities) seems available only when authenticated.
We should have it public as default

**Comment by capooti** [comment]
@tomkralidis this happens because the views behind that url uses the @logged_in_or_basicauth decorator: https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L21
Is it safe to have that view accessible to anyone? Or is it responsible also for transactions? In the latter case we will need to filter out on request types

**Comment by capooti** [comment]
sorry, this is the view: https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L79

**Comment by tomkralidis** [comment]
thanks @capooti.  Suggested update/fix:

- remove `logged_in_or_basicauth()` decorator from https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L79 and https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L21
- update logic in https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L22 as follows:
  - if logged in or basic auth: set CSW-T manager (transactions) to `true`, else `false`

This way, CSW-T only gets enabled at runtime when the client/user is logged in / authenticated / authorized.  Makes sense?

**Comment by capooti** [comment]
thanks, will do it!
