### ISSUE TITLE
urls must provide a dispatcher for accessing layers and services by id

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#250]
Currently it is possible to get to the layer and service page only with uuid (layer_detail and service_detail views). It would be useful to have a way to access to them with the id.

For example, now the layer page is at:
http://hh.worldmap.harvard.edu/registry/hypermap/layer/f0764574-1ef8-11e4-964b-22000aeecbbb/

It would be useful to get to the same page with something like:
http://hh.worldmap.harvard.edu/registry/hypermap/layer/121/id

Same thing for services.

**Comment by zhangmingda** [comment]
fixed

**Comment by capooti** [comment]
well done!
