### ISSUE TITLE
Fix pycsw tests and re-enable them in make test

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#273]
For now I have disabled them:
https://github.com/cga-harvard/HHypermap/commit/30712afaab187aa8f6c247bf6f3d69b580d8b0fb#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by tomkralidis** [comment]
PR issued in #279

**Comment by capooti** [comment]
thanks so much @tomkralidis
