### ISSUE TITLE
Metadata link in layer and service detail page doesn't work

### ISSUE THREAD

**Issue by zhangmingda** [cga-harvard/HHypermap#276]
The id in GetRecordById request should be the uuid.

**Comment by capooti** [comment]
could you fix it? thanks

**Comment by zhangmingda** [comment]
When I changed the id to uuid in layer detail page template, it worked. But in service detail page, I got the following exception: 
<ows:Exception exceptionCode="NotFound" locator="id">
<ows:ExceptionText>
No repository item found for '['ea01b545-95b1-47f5-8c2e-871b5bfb17de']'
</ows:ExceptionText>
</ows:Exception>

**Comment by capooti** [comment]
it may be related to the pycsw configuration. @tomkralidis any hint?

**Comment by tomkralidis** [comment]
Fix issued in PR #278.  Note the pycsw plugin is implemented with Layers as the core model to query, so I've put a workaround for services for CSW `GetRecordById` queries.

**Comment by capooti** [comment]
thanks @tomkralidis
