### ISSUE TITLE
Use appropriate style for administrative actions buttons

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#294]
<img width="985" alt="screenshot 2017-06-09 11 09 25" src="https://user-images.githubusercontent.com/148380/26981818-4a4b4838-4d04-11e7-91c5-404b2aa6b307.png">

It would be nice to use same style as the "Publish" button

**Comment by capooti** [comment]
Both for Layer and Service pages.
Also in Tasks page

**Comment by zhangmingda** [comment]
fixed.
