### ISSUE TITLE
For harvested warper instances, form of remote endpoint is incorrect

### ISSUE THREAD

**Issue by blewis** [cga-harvard/HHypermap#333]
For example, 
For this layer page http://hh.worldmap.harvard.edu/registry/hypermap/layer/1c4e05bf-22b3-4153-8450-f1fdc0253385/

Layer EndPoint: https://mapwarper.h-gis.jp/maps/wms/1621? 
Is incorrect.  It should be 
Layer EndPoint: https://mapwarper.h-gis.jp/maps/1621?
There might be slight differences in form for different warper instances. 

Also Layer Endpoint, which is an attempt to get user to a data download is the most useful of these endpoints and should be first.

**Comment by capooti** [comment]
I disagree on this. If it would be uncorrect MapProxy wouldn't work - which is not the case (test the MapProxy demo). I have tried both endpoints in QGIS and this one https://mapwarper.h-gis.jp/maps/wms/1621 is the correct one.
Can I close this or did I misunderstand you?

**Comment by blewis** [comment]
You are right, it is a good WMS endpoint.  We need something else though for any system that has landing pages for layers where data is downloadable and that is the layer page on the remote system.  Very important for end users.  Perhaps we need to add a line for "Layer Download" and make it first and that would be of the form https://mapwarper.h-gis.jp/maps/1621?.  We had that a long time ago and it disappeared.  The form of this URL will vary from system to system as we build connectors (CKAN, Warper, Rumsey, Esri Open Data, etc) so the logic for creating the Download or Layer Page endpoint would be part of the connector.

**Comment by capooti** [comment]
There is the layer page url for this purpose:

<img width="1033" alt="screenshot 2018-02-26 16 18 31" src="https://user-images.githubusercontent.com/148380/36695939-bd9b9c68-1b10-11e8-96e8-88e2da252457.png">

which is https://mapwarper.h-gis.jp/maps/1621 for this case. Link is correct in Hypermap, but it is not correctly rendered on the page. it is an easy fix

**Comment by blewis** [comment]
No, I'm talking about the landing page for the layer on the remote system (from which one can download the data).  In this case it is on mapwarper.h-gis.jp server and the the URL for this layer is https://mapwarper.h-gis.jp/maps/1621.

**Comment by blewis** [comment]
Sorry I misread you response.  You got it I think.

**Comment by capooti** [comment]
Now I have fixed the html text as well. Only href was  correct.
Thanks @blewis for reporting
