### ISSUE TITLE
MapProxy Integration

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#4]
We need to integrate MapProxy in hypermap.
MapProxy should:

1. cascade services to Web Mercator when is not available
2. cascade WMS
3. cascade Esri REST and enable as OGC services (not sure this is possible)

**Comment by blewis** [comment]
It doesn’t support esri.

To clarify…

All 900913 (and equivalent) WMS will be cached.
All non-900913 WMS will be reprojected and cached.
All 900913 (and equivalent) WMTS will be cached.  (lower priority)
All non-900913 WMS will be reprojected and cached.


Ben Lewis
Center for Geographic Analysis, Harvard University
1737 Cambridge St, K016
617.496.3089
blewis@cga.harvard.edu<mailto:blewis@cga.harvard.edu>
http://gis.harvard.edu<http://gis.harvard.edu/>
http://worldmap.harvard.edu<http://worldmap.harvard.edu/>

**Comment by ingenieroariel** [comment]
This was followed up here: https://github.com/cga-harvard/HHypermap/issues/223
