### ISSUE TITLE
pycsw endpoint

### ISSUE THREAD

**Issue by capooti** [cga-harvard/HHypermap#60]
The endpoint should be this one, according to what I see in urls.py:

http://localhost:8000/search/csw?service=CSW&version=2.0.2&request=GetCapabilities

But I am getting:

AttributeError at /search/csw
'Csw' object has no attribute 'repository'

Exception Location:	/webapps/hypermap/local/lib/python2.7/site-packages/pycsw/ogc/csw/csw2.py in getcapabilities, line 312

**Comment by tomkralidis** [comment]
Fixed in pycsw master branch.

**Comment by capooti** [comment]
Thanks @tomkralidis. Can you make a release?

**Comment by tomkralidis** [comment]
@capooti for sure; we'll be cutting a beta in the next days.
