### ISSUE TITLE
Swagger on Hypermap

### ISSUE THREAD

**Issue by ingenieroariel** [cga-harvard/HHypermap#61]
We need to define what the best Django package is for what we need and which Django API framework it should be based on.

The requirement is that it relies as little as possible on Django models and that it is lightweight and well integrated with Swagger.

This ticket can be closed once the right package has been added to setup.py as a PR.

Let's post the options as comments here and decide together.

**Comment by ingenieroariel** [comment]
@panchicore + @tomkralidis

**Comment by panchicore** [comment]
I've used http://www.django-rest-framework.org/ and APIView works like a regular django View class, so we can do things beyond models, also have an API doc generator for swagger what looks promising https://github.com/marcgibbons/django-rest-swagger

**Comment by panchicore** [comment]
branch: registry. app: search_api

live here http://52.53.174.77:8001/registry/api/docs/#!/default/get_search
