### ISSUE TITLE
CSW HTTP POST requests hang

### ISSUE THREAD

**Issue by tomkralidis** [cga-harvard/HHypermap#94]
In master, running a CSW HTTP POST request hangs/times out.  To reproduce:

### From HHypermap
```bash
python manage.py runserver 0.0.0.0:8000
````

### From another console
```python
import requests
print(requests.post('http://host:8000/search/csw', data='<GetCapabilities xmlns="http://www.opengis.net/cat/csw.2.0.2" service="CSW" version="2.0.2"/>').text)
```

- view in HHypermap: https://github.com/cga-harvard/HHypermap/blob/master/hypermap/search/views.py#L19-L58
- view in GeoNode: https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/views.py#L39-L66

The timeout is rooted in reading the `wsgi.input` environment variable (https://github.com/geopython/pycsw/blob/master/pycsw/server.py#L229)

### Observations
- sending an empty POST works fine (i.e. `print(requests.post('http://host:8000/search/csw', data='').text)`.  The problem arises when there is POST data to read
- the environment is Django's default dev WSGI setup.  We are currently on Django 1.8.7
- attempting the same test in GeoNode (similar enough dev setup, endpoint is instead http://host:8000/catalogue/csw) works fine
- all other WSGI envs (Apache/mod_wsgi) work fine
- we have been advised **not** to rely on the django WSGI server from Django devs (http://django-irc-logs.com/2016/jul/20#2381982)
- perhaps there are slight differences in HHypermap dev setup compared to GeoNode

I realize this is the bare minimum environment and that folks will/should never deploy like this to production, however this is a quick way to stand up an instance which will also help in standing up integration tests in Travis.

**Comment by ingenieroariel** [comment]
This app is a potential workaround for development: Adds a management command to run it using uwsgi:

http://django-uwsgi.readthedocs.io/en/master/command.html
